Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000022DC1D801F0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000022DC23E0D60>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000022DC1B355A0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000022DC1AF36A0>, 1721736.5)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000022DC1B355D0>
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000022DC1B362C0>
transport: <_ProactorSocketTransport fd=844 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Users\Jeval\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\Jeval\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 365, in write
    self._loop_writing(data=bytes(data))
  File "C:\Users\Jeval\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 401, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000022DC1A8C910>
transport: <_ProactorSocketTransport fd=852 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Users\Jeval\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\Jeval\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 365, in write
    self._loop_writing(data=bytes(data))
  File "C:\Users\Jeval\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 401, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
