Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002D3B2834130>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002D3B2E91090>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002D3B25E5540>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000002D3B2608940>, 1721816.781)]']
connector: <aiohttp.connector.TCPConnector object at 0x000002D3B25E5630>
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000002D3B25E6290>
transport: <_ProactorSocketTransport fd=860 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Users\Jeval\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\Jeval\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 365, in write
    self._loop_writing(data=bytes(data))
  File "C:\Users\Jeval\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 401, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000002D3B2FDEF80>
transport: <_ProactorSocketTransport fd=1076 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Users\Jeval\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\Jeval\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 365, in write
    self._loop_writing(data=bytes(data))
  File "C:\Users\Jeval\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 401, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
