Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001ED8A4E00D0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001ED8AB407F0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001ED8A295450>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001ED8AC7CFA0>, 1721312.125)]']
connector: <aiohttp.connector.TCPConnector object at 0x000001ED8A295540>
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000001ED8A2961A0>
transport: <_ProactorSocketTransport fd=688 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Users\Jeval\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\Jeval\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 365, in write
    self._loop_writing(data=bytes(data))
  File "C:\Users\Jeval\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 401, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000001ED8A2953F0>
transport: <_ProactorSocketTransport fd=328 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Users\Jeval\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\Jeval\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 365, in write
    self._loop_writing(data=bytes(data))
  File "C:\Users\Jeval\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 401, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
