Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001D9EBAB0250>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001D9EC109300>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001D9EB8654E0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001D9EC251F60>, 1721494.437)]']
connector: <aiohttp.connector.TCPConnector object at 0x000001D9EB8655D0>
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000001D9EB866230>
transport: <_ProactorSocketTransport fd=896 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Users\Jeval\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\Jeval\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 365, in write
    self._loop_writing(data=bytes(data))
  File "C:\Users\Jeval\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 401, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000001D9EC25B970>
transport: <_ProactorSocketTransport fd=1120 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Users\Jeval\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\Jeval\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 365, in write
    self._loop_writing(data=bytes(data))
  File "C:\Users\Jeval\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 401, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
